внешние курсы/17-asp-net-basics/ASP.NET/PLmvc/Models/RewardViewModel.cs
using HandlerValue;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace PLmvc.Models
{
    public class RewardViewModel
    {
        private string _title;

        private string _description;

        public int ID { get; set; }

        [Required]
        public string Title 
        {
            get { return _title; }
            set
            {
                if (value.Length > InputHandlerValue.MAX_LENGTH_TITLE)
                {
                    throw new ArgumentException();
                }

                _title = value;
            }
        }

        public string Description
        {
            get { return _description; }
            set
            {
                if (value == null)
                {
                    value = "";
                }
                if (value.Length > InputHandlerValue.MAX_LENGTH_DESCRIPTION)
                {
                    throw new ArgumentException();
                }

                _description = value;
            }
        }
    }
}

внешние курсы/17-asp-net-basics/ASP.NET/PLmvc/Controllers/RewardController.cs
using BLL;
using EntityLibrary;
using Microsoft.AspNetCore.Mvc;
using PLmvc.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PLmvc.Controllers
{
    public class RewardController : Controller
    {
        private readonly UserRewardBL _userRewardBL;

        public RewardController(UserRewardBL userBll)
        {
            _userRewardBL = userBll;
        }

        public IActionResult Index()
        {
            return View(_userRewardBL.GetRewards());
        }

        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(RewardViewModel reward)
        {
            _userRewardBL.AddReward(new Reward(0,reward.Title,reward.Description));

            try
            {
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public IActionResult Edit(int id)
        {
            var reward = _userRewardBL.GetRewards().FirstOrDefault(x => x.ID == id);
            return View(new RewardViewModel { ID = reward.ID, Title = reward.Title, Description = reward.Description });
        }

        [HttpPost]
        public IActionResult Edit(RewardViewModel reward)
        {
            _userRewardBL.EditReward((new Reward(reward.ID, reward.Title, reward.Description)));

            try
            {
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public IActionResult Delete(int id)
        {
            var reward = _userRewardBL.GetRewards().FirstOrDefault(x => x.ID == id);
            return View(new RewardViewModel { ID = reward.ID, Title = reward.Title, Description = reward.Description });
        }

        [HttpPost]
        public IActionResult Delete(RewardViewModel reward)
        {
            _userRewardBL.RemoveReward(reward.ID);

            try
            {
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

внешние курсы/17-asp-net-basics/ASP.NET/PLmvc/Views/Reward/Add.cshtml
@model RewardViewModel

<h3 class="display-4">Add reward</h3>
<br />
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="Reward" asp-action="Add" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Add" class="btn btn-outline-primary btn-block" />
            </div>
        </form>

        <form asp-controller="Reward" asp-action="Index">
            <div class="form-group">
                <button type="submit" class="btn btn-outline-secondary btn-block">Back</button>
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

внешние курсы/17-asp-net-basics/ASP.NET/PLmvc/Views/Reward/Delete.cshtml
@model RewardViewModel

    <br />
    <h1 class="display-4">Are you sure you want to delete this reward?</h1>
    <br />
    <div>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.ID)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.ID)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Title)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Title)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Description)
            </dt>
            <dd class="col-sm-4">
                @Html.DisplayFor(model => model.Description)
            </dd>
        </dl>
        <div class="col-3">
            <form asp-controller="Reward" asp-action="Delete">
                <div class="form-group">
                    <button type="submit" class="btn btn-outline-danger btn-block">Delete</button>
                </div>
            </form>
            <form asp-controller="Reward" asp-action="Index">
                <div class="form-group">
                    <button type="submit" class="btn btn-outline-secondary btn-block">Back</button>
                </div>
            </form>
        </div>
    </div>

внешние курсы/17-asp-net-basics/ASP.NET/PLmvc/Views/Reward/Edit.cshtml
@model RewardViewModel

<h1 class="display-4">Edit reward</h1>
<br />
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="Reward" asp-action="Edit" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group" hidden>
                <label asp-for="ID" class="control-label"></label>
                <input asp-for="ID" class="form-control" />
                <span asp-validation-for="ID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-outline-success btn-block" />
            </div>
        </form>
        <form asp-controller="Reward" asp-action="Index">
            <div class="form-group">
                <button type="submit" class="btn btn-outline-secondary btn-block">Back</button>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

внешние курсы/17-asp-net-basics/ASP.NET/PLmvc/Views/Reward/Index.cshtml
@model IEnumerable<EntityLibrary.Reward>

<div class="col-10">
    <h3 class="display-4">Rewards</h3>
</div>
<div class="row">
    <div class="col-10">

    </div>
    <div class="col-2">
        <p>
            <a asp-action="Add" class="btn btn-outline-primary btn-block" role="button">Add</a>
        </p>
    </div>
</div>


<table class="table table-hover">
    <thead class="thead-light">
        <tr>
            <th hidden>
                @Html.DisplayNameFor(model => model.ID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td hidden>
                    @Html.DisplayFor(modelItem => item.ID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    <div class="form-group">
                        <a href="Reward/Edit/@item.ID" class="btn btn-outline-success btn-sm btn-block" role="button">Edit</a>
                    </div>
                    <div class="form-group">
                        <a href="Reward/Delete/@item.ID" class="btn btn-outline-danger btn-sm btn-block" role="button">Delete</a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>